# Generated by Django 6.0 on 2025-12-09 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('violencia', 'Violência Urbana'), ('saneamento', 'Saneamento Básico'), ('planejamento', 'Infraestrutura e Mobilidade'), ('meioambiente', 'Meio Ambiente')], max_length=20)),
                ('subtema', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnexoDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='denuncias/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.denuncia')),
            ],
        ),
    ]
